version: '3'

services:
  app:
    build: ./app
    container_name: app
    command: gunicorn --bind 0.0.0.0:5000 main:app
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2RTY4356
      - POSTGRES_DB=ktl_db
    volumes:
      - ./db/scripts:/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
      - pgadmin
